services:
#####################
# Redpanda
######################
  redpanda:
    image: redpandadata/redpanda:v25.3.4
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092 
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092 # 
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - redpanda_network


  console:
    image: redpandadata/console:latest
    container_name: redpanda_console
    depends_on:
      - redpanda
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
    networks:
      - redpanda_network

#####################
# Python producer ticket client
######################

  python_source:
    build:
      context: .
      dockerfile: dockerfile
    container_name: python_source
    volumes:
      - ./scripts:/app
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - redpanda_network


#################
# Spark Master et 2 workers
######################

  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "7077:7077"   
      - "8080:8080"  
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5 
    networks:
      - redpanda_network

  spark-worker-1:
    image: apache/spark:3.5.3
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    command: >
     /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - redpanda_network

  spark-worker-2:
    image: apache/spark:3.5.3
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    command: >
     /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - redpanda_network


#################
# Job avec Pysparks et script 
######################

  spark-job:
    image: apache/spark:3.5.3
    container_name: spark-job
    depends_on:
      spark-master:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    volumes:
      - ./scripts:/app/scripts
      - ./output:/app/output          
      - ./checkpoint:/app/checkpoint
    command: > 
       /opt/spark/bin/spark-submit 
       --master spark://spark-master:7077 
       --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3 
       --deploy-mode client 
       --driver-java-options -Divy.cache.dir=/tmp\ -Divy.home=/tmp 
       --conf spark.pyspark.python=python3 
       /app/scripts/consumer.py
    networks:
      - redpanda_network


volumes:
  redpanda_data:

networks:
  redpanda_network:
    driver: bridge
