FROM python:3.12-slim

WORKDIR .

# Copier
COPY requirements.txt .
COPY scripts/ app/

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app/producer.py"]

